networks:
  skyline_net:
    external: true

services:
  postgres:
    container_name: skyline_postgres
    hostname: skyline|postgres
    image: postgres:15.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - skyline_net

  redis:
    container_name: skyline_redis
    hostname: skyline|redis
    image: redis:5.0.5-alpine
    networks:
      - skyline_net

  mailhog:
    container_name: skyline_mailhog
    hostname: skyline|mailhog
    image: mailhog/mailhog:v1.0.1
    entrypoint: MailHog -jim-accept 1.0	-jim-reject-recipient	1.0
    networks:
      - skyline_net
